Changes:  - regenerated lexer and parser because it fixed the following error I got on    my machine at home.
   error: 'yy_current_buffer' was not declared in this scope



git-svn-id: https://svn.win.tue.nl/repos/MCRL2/trunk@2032 21252fe5-60e8-0310-8ff0-c1ae1001594e