Made a few more changes, because the compiler of Wieger indicates compilation errors. My own compiler only indicates link errors. E.g. I get:
gcc.compile.c++ /home/jfg/MCRL2/build/bin/pbes2bes/gcc-4.1.1/debug/address-model-32/pbes2bool.o
gcc.link /home/jfg/bin/pbes2bool
/home/jfg/MCRL2/build/bin/pbes2bes/gcc-4.1.1/debug/address-model-32/pbes2bool.o: In function `squadt_interactor::perform_task(tipi::configuration&)':
/home/jfg/MCRL2/tools/pbes2bes/pbes2bool.cpp:256: undefined reference to `process(t_tool_options const&)'
/home/jfg/MCRL2/build/bin/pbes2bes/gcc-4.1.1/debug/address-model-32/pbes2bool.o: In function `main':
/home/jfg/MCRL2/tools/pbes2bes/pbes2bool.cpp:279: undefined reference to `process(t_tool_options const&)'
collect2: ld returned 1 exit status

I have no idea what the cause of these discrepancies is.
svn status and svn diff indicate that my distribution of the toolset is not different
from the standard distribution.




git-svn-id: https://svn.win.tue.nl/repos/MCRL2/trunk@3357 21252fe5-60e8-0310-8ff0-c1ae1001594e