Changes:  - workaround for compiler error:
    call "C:\Program Files\Microsoft Visual Studio 9.0\VC\vcvarsall.bat" x86 >nul
cl /Zm800 -nologo @"C:\msys\workspace\regression\results\toolset\libraries\lps\build\msvc-9.0\debug\asynch-exceptions-on\link-static\pch-off\stdlib-stlport-5.2.1\threading-multi\implementations.obj.rsp" 

implementations.cpp
C:\msys\workspace\regression\mcrl2\libraries\data\include\mcrl2/data/structured_sort.h(176) : fatal error C1004: unexpected end-of-file found


git-svn-id: https://svn.win.tue.nl/repos/MCRL2/trunk@6495 21252fe5-60e8-0310-8ff0-c1ae1001594e