- Migrated lps library to namespace mcrl2::lps. - Migrated modal formulas to namespace mcrl2::modal. - Migrated pbes library to namespace mcrl2::pbes_system. - Applied many corrections (missing include files, improper uses of namespace qualifiers, etc.).
Better names for the namespaces might be chosen. I don't think it is a good idea to let the namespace name clash with a datatype (like in case of the lts library). This very easily results in ambiguities.

Currently pbes2bool doesn't compile with Visual C++ because of the following error message:
pbes2bool.cpp
C:\Program Files\Microsoft Visual Studio 8\VC\INCLUDE\ostream(581) : error C2248: 'std::basic_ios<_Elem,_Traits>::basic_ios' : cannot access private member declared in class 'std::basic_ios<_Elem,_Traits>'
It probably has to do with the usage of ios::trunc, but I have no clue what's wrong with it.


git-svn-id: https://svn.win.tue.nl/repos/MCRL2/trunk@4090 21252fe5-60e8-0310-8ff0-c1ae1001594e